version: '3'

services:
# APP  ***************************************************************************************
  spring-boot-mongo-docker: 
    image: jbjares/spring-boot-hpdms:v1
    ports:
    - 80:8080
    links:
    - mongo
    depends_on:
    - mongo
    command: bash -c "cd /app/services && mvn install -DskipTests && mvn spring-boot:run"


# DB  ***************************************************************************************
  mongo:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/db.log
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

    
    
    